data: 
  id: "Ankursingh/openwebtext_10K" 
  cache_dir: "/content/cache"
  tokenizer: "NousResearch/Llama-2-7b-hf"
  stream: false

model:
  type: llama
  hidden_dim: 576
  intermediate_dim: 2304  # 4x hidden_dim
  num_heads: 12  
  num_layers: 12  
  seq_len: 512

trainer:
  wandb:
    name: "nano_llama"
    project: "qkvflow"
    tags: ["ankursingh", "nano", "llama"]
  
  mp: p=f32,c=bfloat16
  per_device_eval_parallelism: 1
  per_device_parallelism: 1
  train_batch_size: 12           
  num_train_steps: 5000 
  steps_per_eval: 100   
  
  tensor_parallel_axes: ["mlp", "heads"]
  fsdp_axis: "embed"
  batch_axis: "batch"
  
  checkpointer: 
    save_interval: 45min 
    keep:
      - every: 1000
        until: 5001
    base_path: "/content/drive/MyDrive/nano_llama_checkpoints/"

optimizer:
  learning_rate: 4E-4 
  beta2: 0.95
  weight_decay: 1e-5
  min_lr_ratio: 0.1
  epsilon: 1e-8

model_choice: llama
time_embed_dim: 24 
sinusodial_dim: 96 